### ISSUE TITLE
Does not work on mac.

### ISSUE THREAD

**Issue by chadify** [0x-DLN/obsidian-table-checkboxes#18] opened 2024-10-18 07:01 UTC
Here's the attached video:

https://github.com/user-attachments/assets/b583fef1-1aa1-4e24-9389-651f3b896abd

**Comment by LennartCode** [comment] 2024-11-27 12:13
Possible duplicate of #11

**Comment by 0x-DLN** [comment] 2024-12-20 22:03
Should be fixed in 3.0.0

**Closed by 0x-DLN** 2024-12-20 22:03 UTC
